### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by mciszczon** [HermanNygaard/react-scroll-to-top#1]
Hi there! Thanks for this cool little lib! I'm adding it to one of my projects right now and thought that having the smooth scroll feature would be great.

I see that you use:

```javascript
document.documentElement.scrollTop = 0
```

in your code, but if you switched to using:

```javascript
window.scrollTo({ top: 0, behavior: 'smooth' })
```

then it would work out of the box for most of the browers ([here's a Can I Use page for this feature](https://caniuse.com/#feat=css-scroll-behavior)). It could be implemented as a opt-in feature (just adding a bool prop `smooth` would do the trick).

What do you think? I could make a PR of course if you want.

**Comment by HermanNygaard** [comment]
Hi!

I totally agree. I'm not sure if we should have it enabled by default or as a prop, but I think adding it as a prop is a good solution for now. What do you think?
Please make a PR if you'd like!

**Comment by mciszczon** [comment]
@HermanNygaard I have created a PR #2 :)

**Comment by HermanNygaard** [comment]
Thank you very much! This works great
