### ISSUE TITLE
Component disappears when you add className property

### ISSUE THREAD

**Issue by muhammed-mustafa-helal** [HermanNygaard/react-scroll-to-top#29]
Component disappears when you add a className property

**Comment by harrytran103** [comment]
Hi all, I think it should have 2 props for CSS classes
- className: can extend the base css class
- overrideClass: override the base css class

@HermanNygaard @muhammed-mustafa-helal

**Comment by HermanNygaard** [comment]
not sure how to do make the className extendable without the user having to import the stylesheet (its bundled up in the dist JS now so you don't have to import anything), feel free to make a PR

**Comment by YinChuRijnaard** [comment]
I'm experiencing the same issue. Additional question, can it be used with Tailwind CSS? I tried to add some classes but then it disappears.

**Comment by HermanNygaard** [comment]
I have made it so the className will be extended instead in v3. You might need to add `!important` for specific overrides
