### ISSUE TITLE
(Question NOT Issue) New to React: how to increase the bottom padding of component

### ISSUE THREAD

**Issue by willemevenwel** [HermanNygaard/react-scroll-to-top#3]
Hi,

I'm very new to react, pardon the novice question. What parameters do I need to change to increase the bottom padding of the component?

Regards,

Willem

**Comment by HermanNygaard** [comment]
Hi Willem!

Thank you for the question. You can either use a custom classname or a React style object.
Example with a style object: 
```jsx
<ScrollToTop smooth style={{paddingBottom: 50}} />
```
