### ISSUE TITLE
problem with npm install

### ISSUE THREAD

**Issue by tmhuyy** [HermanNygaard/react-scroll-to-top#37]
![Screenshot 2022-06-09 at 01 57 46](https://user-images.githubusercontent.com/96604960/172695262-9faa4b8b-dbff-4dd0-a68f-e35c8bf85e57.png)

**Comment by HestonB** [comment]
Same issue with me

**Comment by HermanNygaard** [comment]
ty, peerdeps updated to allow react 18 now
