### ISSUE TITLE
Arrow isn't centered

### ISSUE THREAD

**Issue by YinChuRijnaard** [HermanNygaard/react-scroll-to-top#41]
When using the ScrollToTop component, the arrow in the box isn't centred.

I didn't add any other code. 

Repo, (index.tsx): https://github.com/YinChuRijnaard/Portfolio-v3 (exact commit: https://github.com/YinChuRijnaard/Portfolio-v3/commit/5cf0100670f6c2a84fcd8a5928ea8bc854956e96).

<img width="612" alt="Screenshot 2022-07-11 at 18 25 40" src="https://user-images.githubusercontent.com/65867865/178312837-386fcd2a-2681-4c6c-8069-036116717133.png">

**Comment by YinChuRijnaard** [comment]
Excuse me, I thought I changed the visibility.

Do you still wish to see a CodeSandbox? :)

**Comment by YinChuRijnaard** [comment]
Alright, thank you for this information. How would I be able to inspect such things myself in the future? Simply with the dev tools?

**Comment by HermanNygaard** [comment]
Yup, I inspected the svg element in devtools

**Comment by YinChuRijnaard** [comment]
Okay, thanks again for your time! Closing this issue 👍🏼
