### ISSUE TITLE
This works great but how do I replace the default SVG

### ISSUE THREAD

**Issue by davidrhoderick** [HermanNygaard/react-scroll-to-top#5]
My designer sent me a branded SVG and this one won't do.  Is there any way to change it?

**Comment by HermanNygaard** [comment]
Hi David!

I will work on a new release that will include this now. It should be ready soon. It will have props for the SVG path and the SVG viewbox, is that sufficient?

**Comment by davidrhoderick** [comment]
Wow awesome, I think that would work.  If I import the SVG into my React app, I'll be able to set it as the path that way, correct?

**Comment by HermanNygaard** [comment]
It is live now. Update to the newest version, [here is an example](https://codesandbox.io/s/react-scroll-to-top-custom-svg-or74g?file=/src/App.js:247-269)
Let me know if it works out for you

**Comment by davidrhoderick** [comment]
@HermanNygaard great job on adding the ability to change the icon!  Sorry for the delay but I've just been overloaded lately so I only got to trying it.
