### ISSUE TITLE
Does not work on Desktop Safari Browser

### ISSUE THREAD

**Issue by jericopulvera** [HermanNygaard/react-scroll-to-top#7]
The button is not appearing.

**Comment by HermanNygaard** [comment]
Could you elaborate? What does not work? It works fine for me on Safari, what version are you using?

**Comment by jericopulvera** [comment]
> Could you elaborate? What does not work? It works fine for me on Safari, what version are you using?

MacOS Mojave
Safari 12.1.2

**Comment by patotoma** [comment]
same thing on iOS
